name: Clone hello-jni app folder
on: workflow_dispatch

jobs:
  clone:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # penting! biar bisa pull/push

      - name: Sparse clone folder app doang
        run: |
          git clone --depth 1 --filter=blob:none --sparse https://github.com/android/ndk-samples temp
          cd temp
          git sparse-checkout set hello-jni/app
          cp -r hello-jni/app/*../
          cd..
          rm -rf temp

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add --all
          git commit -m "Clone hello-jni/app from NDK samples" || echo "No changes"

          git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${REPO}.git"

          BRANCH="${GITHUB_REF#refs/heads/}"
          if [ -z "$BRANCH" ]; then
            BRANCH="main"
          fi

          git push origin "HEAD:${BRANCH}" --force
